config/routes.rb
Rails.application.routes.draw do
  namespace :v1, defaults: { format: 'json' } do
    get 'greeting', to: 'greetings#random'
  end

  get '*page', to: 'users#index', constraints: ->(req) do
    !req.xhr? && req.format.html?
  end

  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/greeting.rb
class Greeting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def hello; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/controllers/v1/greetings_controller.rb
class V1::GreetingsController < ApplicationController
  before_action :set_greeting, only: %i[show edit update destroy]

  # GET /greetings or /greetings.json
  def random
    random = Random.new
    @greeting = Greeting.find(random.rand(1..5))
    render json: {
      greeting: @greeting.greeting.to_s
    }.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/greetings/_form.html.erb
<%= form_with(model: greeting) do |form| %>
  <% if greeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(greeting.errors.count, "error") %> prohibited this greeting from being saved:</h2>

      <ul>
        <% greeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/greetings/edit.html.erb
<h1>Editing Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Show', @greeting %> |
<%= link_to 'Back', greetings_path %>

app/views/greetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Greetings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @greetings.each do |greeting| %>
      <tr>
        <td><%= link_to 'Show', greeting %></td>
        <td><%= link_to 'Edit', edit_greeting_path(greeting) %></td>
        <td><%= link_to 'Destroy', greeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Greeting', new_greeting_path %>

app/views/greetings/new.html.erb
<h1>New Greeting</h1>

<%= render 'form', greeting: @greeting %>

<%= link_to 'Back', greetings_path %>

app/views/greetings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_greeting_path(@greeting) %> |
<%= link_to 'Back', greetings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorReactHello</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= react_component("App") %>